name: FTP Deploy
on:
  push:
    branches:
      - master  # Set this to the branch you want to deploy from

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    name: Deploy via FTP
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18'

    - name: Build
      run: |
        npm install
        npm run production  # or any other build scripts you use

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USER }}
        ftp-password: ${{ secrets.FTP_PASS }}
        local-dir: /dev.codeforsite.com  # Directory to upload
        git-ftp-args: --insecure  # Use this if your FTP server does not support FTP over TLS
