name: FTP Deploy
on:
  push:
    branches:
      - master  # Set this to the branch you want to deploy from

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    name: Deploy via FTP
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: FTP Deployer
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        host: ${{ secrets.FTP_SERVER }} # e.g. ftp.host.com or sftp.host.com (without ftp:// or sftp://)
        port: 22 # optional, default is: 21
        username: ${{ secrets.FTP_USER }} # FTP username
        password: ${{ secrets.FTP_PASS }} # FTP password
        local-dir: ./ # Adjust to the directory you want to deploy
        remote_folder: /dev.codeforsite.com
